app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
hello:
    path:      /hello/{name}
    # uses a special syntax to point to the controller - see note below
    defaults:  { _controller: AppBundle:Hello:index }

blog_index:
    path: /blog
    defaults: {_controller: AppBundle:Blog:index}
    requirements: {_method: GET}

user_index:
    path: /user
    defaults: {_controller: AppBundle:User:index}

user_create:
    path: /user/create
    defaults: {_controller: AppBundle:User:create}

user_show:
    path: /user/show/{sUserName}
    defaults: {_controller: AppBundle:User:show}

user_store:
    path: /user/store
    defaults: {_controller: AppBundle:User:store}

user_delete:
    path: /user/delete/{sUserName}
    defaults: {_controller: AppBundle:User:delete}